import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google"; import fonts here
import { DM_Sans } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";

const dmSans = DM_Sans({
	variable: "--font-primary",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Shruti Patnekar | Psychologist",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className={`${dmSans.variable} font-primary`}>
			<body>
				<main className={`max-w-6xl mx-4 mt-5 lg:mx-auto antialiased`}>
					<NavBar />

					{children}
				</main>
				<Footer />
			</body>
		</html>
	);
}
